### ISSUE TITLE
[BUG]: Add file contents

### ISSUE THREAD

**Issue by troutacular** [uscwebservices/usc-wordpress-pantheon-upstream-gateway-sso-xml#620]
Adding build message to PR having issues.

```
Run echo 'build_message<<EOF' >> $GITHUB_ENV echo "${ steps.read_build_message.outputs.contents }" >> $GITHUB_ENV echo 'EOF' >> $GITHUB_ENV
  echo 'build_message<<EOF' >> $GITHUB_ENV echo "${ steps.read_build_message.outputs.contents }" >> $GITHUB_ENV echo 'EOF' >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
  env:
    API_TOKEN_GITHUB: ***
    TERMINUS_TOKEN: ***
    TERMINUS_ORG_ID: ***
    TERMINUS_UPSTREAMS: ***
    TERMINUS_UPSTREAMS_WORDPRESS_WEB: ***
    TERMINUS_UPSTREAMS_WORDPRESS_ROOT:  
    TERMINUS_UPSTREAMS_DRUPAL_WEB:  
    TERMINUS_UPSTREAMS_DRUPAL_ROOT:  
    branch_timestamp: 2024-04-22-16-40-40
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
/home/runner/work/_temp/aeeab4f6-0994-434b-aa6e-c3d22c633ed7.sh: line 1: ${ steps.read_build_message.outputs.contents }: bad substitution
```
